name: Push Trigger

on:
  push:  # Trigger this workflow on any push to any branch
    branches:
      - '**'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "✅ A commit was pushed, and this action ran successfully!"
