name: Push Trigger

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  show-push-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show pushed files
      run: |
        echo "The following files were pushed:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}
